#ifndef CARDEFFECT_H
#define CARDEFFECT_H

typedef enum {
    TIMING_LOCK,
    TIMING_ONATTACK
}TIMING;
typedef struct {
    char name[32];

} CardEffect;

typedef enum {
    CARDEFFECT_COPYTOUSED,
    CARDEFFECT_DEALBYBLOCK,
    CARDEFFECT_ONLYATTACKCARDS,
    CARDEFFECT_USEDTOPULLTOP,
    CARDEFFECT_3TIMESPOWER,
    CARDEFFECT_5TIMESPOWER,
    CARDEFFECT_2DAMAGEPERSTRIKE,
    CARDEFFECT_3DAMAGEPERSTRIKE,
    CARDEFFECT_DROW,
    CARDEFFECT_2DROW,
    CARDEFFECT_3DROW,
    CARDEFFECT_4DROW,
    CARDEFFECT_5DROW,
    CARDEFFECT_WOUNDTOPULL,
    CARDEFFECT_LOSEHPTOLOSECOST,
    CARDEFFECT_VOLATILITY,
    CARDEFFECT_VULNERABLETOCOSTANDDROW,
    CARDEFFECT_2HPLOSE,
    CARDEFFECT_5DAMAGEINCREASE,
    CARDEFFECT_8DAMAGEINCREASE,
    CARDEFFECT_NOLIMITUPGRADE,
    CARDEFFECT_EXHAUSTEALLCARDNOATTACK,
    CARDEFFECT_DAZEDTOPULL,
    CARDEFFECT_FATALTO3MAXHP,
    CARDEFFECT_FATALTO4MAXHP,
    CARDEFFECT_7DAMAGEPEREXHAUSTALL,
    CARDEFFECT_10DAMAGEPEREXHAUSTALL,
    CARDEFFECT_BURNTOUSED,
    CARDEFFECT_NONBLOCKEDDANAGETOHEAL,

    CARDEFFECT_TOTAL_COUNT
}
extern 
#endif